name : continuous integration

on:
    pull_request:
        branches: 
            - staging
            - main

jobs:
    quality:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: set up python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Install Dependencies
              run: uv sync

            - name: lint with Ruff
              run: uv run ruff check .

            - name: format check with Black
              run: uv run black --check .

            - name: import check with isort
              run: uv run isort --check-only .

            - name: Type Check with MyPy
              run: uv run mypy .

            - name: Run Tests & Coverage
              run: uv run pytest

            - name: Verify Workflow
              run: echo "CI pipeline executed successfully."
